apiVersion: apps/v1
kind: Deployment
metadata:
  name: floodapp
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: predictor
          image: emreyldzgl/floodapp
          ports:
            - containerPort: 8501